import Vue from 'vue'
import { Dialog, ActionSheet, Icon, Button, Rate, Tabbar, TabbarItem, NavBar, Toast, Swipe, SwipeItem, Grid, Search, GridItem } from 'vant'
Vue.use(Dialog)
Vue.use(ActionSheet)
Vue.use(Button)
Vue.use(Rate)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(NavBar)
Vue.use(Toast)
Vue.use(Swipe)
Vue.use(Grid)
Vue.use(Search)
Vue.use(GridItem)
Vue.use(SwipeItem)
Vue.use(Icon)
